from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any, Protocol, Callable

from opencode_voice.config import ModelRef


class AgentBackend(Protocol):
    """
    Provider-neutral interface for a coding agent that can host voice sessions.

    A concrete implementation wraps the agent's HTTP/WS API and translates
    its wire shapes into the neutral types used by the voice lane.
    """

    async def health(self) -> dict[str, Any]: ...
    async def list_sessions(self) -> list[dict[str, Any]]: ...
    async def create_session(self) -> dict[str, Any]: ...
    async def get_session(self, session_id: str) -> dict[str, Any]: ...
    async def fork_session(self, session_id: str, message_id: str | None = None) -> dict[str, Any]: ...
    async def update_session(self, session_id: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def delete_session(self, session_id: str) -> Any: ...
    async def abort(self, session_id: str) -> Any: ...
    async def messages(self, session_id: str) -> list[dict[str, Any]]: ...
    async def prompt_text(self, session_id: str, text: str, model: ModelRef, agent: str) -> Any: ...
    async def events(self, on_open: Callable[[], None] | None, directory: str | None) -> AsyncIterator[dict[str, Any]]: ...
    async def close(self) -> None: ...
    async def switch_model(self, session_id: str, model: ModelRef) -> Any: ...
    async def switch_agent(self, session_id: str, agent: str) -> Any: ...
    async def prompt_async(
            self,
            session_id: str,
            text: str,
            model: ModelRef,
            agent: str,
            *,
            output_format: dict[str, Any] | None = None,
            system: str | None = None,
            tools: dict[str, bool] | None = None,
    ) -> Any: ...
    async def summarize(self, session_id: str, model: ModelRef, auto: bool = False) -> Any: ...
    async def agents(self) -> list[str]: ...
