from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Any, Protocol


class AgentBackend(Protocol):
    """
    Provider-neutral interface for a coding agent that can host voice sessions.

    A concrete implementation wraps the agent's HTTP/WS API and translates
    its wire shapes into the neutral types used by the voice lane.
    """

    async def health(self) -> dict[str, Any]: ...
    async def list_sessions(self) -> list[dict[str, Any]]: ...
    async def create_session(self) -> dict[str, Any]: ...
    async def get_session(self, session_id: str) -> dict[str, Any]: ...
    async def fork_session(self, session_id: str, message_id: str | None = None) -> dict[str, Any]: ...
    async def delete_session(self, session_id: str) -> Any: ...
    async def abort(self, session_id: str) -> Any: ...
    async def messages(self, session_id: str) -> list[dict[str, Any]]: ...
    async def prompt_text(self, session_id: str, text: str, model: Any, agent: str) -> Any: ...
    async def events(self, on_open: Any, directory: str | None) -> AsyncIterator[dict[str, Any]]: ...
    async def close(self) -> None: ...