/**
 * Regenerates the checked-in protocol artifacts from schema.ts:
 *
 *   protocol/mortic.sidepod.v0.schema.json      canonical JSON Schema document
 *   opencode_mercury_sidepod/src/protocol.gen.mjs   plugin runtime copy (zero deps)
 *   opencode_voice/protocol_schema.json         helper runtime copy (wheel-packaged)
 *
 * Run from this directory: `npm run gen` (Node >= 22.18 runs the .ts directly).
 * Every artifact embeds the SHA-256 of schema.ts; test suites on both sides
 * recompute that hash, so schema edits that skip regeneration fail the gates.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { COMMANDS, EVENTS, PROTOCOL_VERSION } from "./schema.ts";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");

const sourceHash = createHash("sha256")
  .update(readFileSync(join(here, "schema.ts")))
  .digest("hex");

function toJsonSchema(schema: z.ZodType): Record<string, unknown> {
  const out = z.toJSONSchema(schema, { target: "draft-2020-12" }) as Record<string, unknown>;
  delete out.$schema;
  return sortKeysDeep(out) as Record<string, unknown>;
}

/** Deterministic output regardless of zod internals: sort object keys deeply. */
function sortKeysDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
        .map(([k, v]) => [k, sortKeysDeep(v)]),
    );
  }
  return value;
}

const mapAll = (registry: Record<string, z.ZodType>) =>
  Object.fromEntries(
    Object.entries(registry).map(([name, schema]) => [name, toJsonSchema(schema)]),
  );

const document = {
  title: "Mortic Sidepod <-> Engine protocol v0",
  protocolVersion: PROTOCOL_VERSION,
  "x-source-hash": sourceHash,
  "x-generated-by": "protocol/generate.ts",
  commands: mapAll(COMMANDS),
  events: mapAll(EVENTS),
};

const json = JSON.stringify(document, null, 2) + "\n";

writeFileSync(join(here, "mortic.sidepod.v0.schema.json"), json);
writeFileSync(join(repoRoot, "opencode_voice", "protocol_schema.json"), json);

const mjs = `// Generated by protocol/generate.ts — do not edit. Source: protocol/schema.ts
export const PROTOCOL_VERSION = ${JSON.stringify(PROTOCOL_VERSION)};
export const SOURCE_HASH = ${JSON.stringify(sourceHash)};
export const PROTOCOL_SCHEMA = ${JSON.stringify(document, null, 2)};
export const COMMAND_TYPES = Object.freeze(Object.keys(PROTOCOL_SCHEMA.commands));
export const EVENT_TYPES = Object.freeze(Object.keys(PROTOCOL_SCHEMA.events));
`;
writeFileSync(join(repoRoot, "opencode_mercury_sidepod", "src", "protocol.gen.mjs"), mjs);

console.log(`generated protocol artifacts (source hash ${sourceHash.slice(0, 12)}…)`);
